FROM golang:1.20.4-alpine3.17
WORKDIR /app
COPY . .
RUN go env -w GOPROXY=https://goproxy.cn,direct \
    && go build --ldflags "-s -w" -race -o ./build/app ./cmd/main.go

FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
LABEL description="golang,app"
RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add tzdata
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY --from=0 /app/conf/config-dev.yaml ./conf/
COPY --from=0 /app/build/app ./build/
RUN apk add --no-cache shadow && \
    useradd -U -u 1000 appuser && \
    chown -R 1000:1000 /app
USER 1000
CMD [ "./build/app"]

